---
title: "Paper Figures"
format: html
---

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
```

```{r}
prediction_dat <- read_csv(
  "../data/resnet-age-outcomes.csv",
  name_repair = janitor::make_clean_names,
  col_types = cols(
    x = col_skip(),
    subject_id = col_double(),
    hadm_id = col_double(),
    stay_id = col_double(),
    gender = col_character(),
    admission_age = col_double(),
    admittime = col_datetime(format = ""),
    dischtime = col_datetime(format = ""),
    icu_intime = col_datetime(format = ""),
    icu_outtime = col_datetime(format = ""),
    hospital_expire_flag = col_double(),
    study_id = col_double(),
    ecg_time = col_datetime(format = ""),
    ecg_order = col_double(),
    age_pred = col_double()
  )
)
```

```{r}
fig <- prediction_dat %>%
  filter(!is.na(age_pred)) %>%
  ggplot(aes(admission_age, age_pred)) +
  geom_hex() +
  geom_abline(slope = 1,
              intercept = 0,
              color = 'red') +
  scale_fill_continuous(trans = "log10") +
  stat_cor() + 
  theme_bw(base_size = 14) +
  labs(y = "Predicted Age, y",
       x = "Actual Age, y",
       fill = "Count",
       title = "Actual versus Predicted Age")

ggsave("figure-actual-versus-predicted.eps", fig, width = 6, height = 4)
fig
```

```{r}
fig <- 
  prediction_dat %>%
  filter(!is.na(age_pred)) %>%
  mutate(delta_age = age_pred - admission_age,
         age_bin = cut_number(admission_age, n = 5)) %>%
  ggplot(aes(delta_age, color = age_bin, fill = age_bin)) +
    geom_density(alpha = 0.3) +
    scale_color_discrete(guide = NULL) + 
    coord_cartesian(expand = FALSE) + 
    theme_bw(base_size = 14) +
    labs(x = "Predicted - Actual Age", y = "Density", fill = "Age Quintile")

ggsave("figure-error-density.eps", fig, width = 6, height = 4)
fig
```

```{r}
fig <- 
  prediction_dat %>%
  ggplot(aes(admission_age)) +
    geom_histogram(binwidth = 1) +
    coord_cartesian(expand = FALSE) + 
    theme_bw(base_size = 14) + 
    labs(y = "Count of Patients", x = "Age")

ggsave("figure-age-distribution.eps", fig, width = 6, height = 4)
fig
```



```{r}
fig <-
  fs::dir_ls("../data/", glob = "*-history.csv") %>%
  set_names() %>%
  map(~read_csv(.x, show_col_types = FALSE)) %>%
  list_rbind(names_to = "model") %>%
  mutate(model = str_replace(model, ".*/", "") %>% str_replace("-history.csv", "")) %>%
  separate(model, c("arch", "task"), remove = FALSE) %>%
  mutate(task = if_else(task == "age2", "age", task)) %>%
  select(model, task, epoch, loss, val_loss) %>%
  pivot_longer(c(loss, val_loss)) %>%
  ggplot(aes(epoch, value, linetype = name, color = model)) +
    geom_line() +
    facet_wrap(~task, scales="free_y") +
    scale_linetype_discrete(labels = c("Training", "Validation")) + 
    theme_bw(base_size = 14) +
    labs(y = "Loss", x = "Epoch", color = "Model", linetype = "") 

ggsave("figure-training-loss.eps", fig, width = 8, height = 4)
fig
```

